### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by MrMooky** [statamic/eloquent-driver#14]
I just installed this package, ran the migrations and get the error `Class name must be a valid object or a string` when accessing the CP or any Collection in the frontend.

Error is in file `vendor/statamic/eloquent-driver/src/ServiceProvider.php` on line 44. Am I missing something important? There's not really much documented for the setup so I'd figure it was straightforward.

<img width="613" alt="Screenshot 2021-03-01 at 13 51 28" src="https://user-images.githubusercontent.com/3603346/109499483-4027d480-7a95-11eb-97a7-b165aa449610.png">

**Comment by jasonvarga** [comment]
Can you run `php please support:details`?

**Comment by MrMooky** [comment]
@jasonvarga Sure:

Statamic 3.0.45 Pro
Laravel 8.29.0
PHP 7.4.8
mitydigital/statamic-tinymce-cloud 1.0.3
pecotamic/sitemap 1.1.0
statamic/eloquent-driver 0.1.1

**Comment by jasonvarga** [comment]
Can you provide the whole error's stack trace?

**Comment by MrMooky** [comment]
```
[2021-03-01 15:24:24] local.ERROR: Class name must be a valid object or a string {"userId":"3965cec0-b8ad-49c7-829d-887383695663","exception":"[object] (Error(code: 0): Class name must be a valid object or a string at /Users/mooky/Code/stellaprojects/vendor/statamic/eloquent-driver/src/ServiceProvider.php:44)
[stacktrace]
#0 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Statamic\\Eloquent\\ServiceProvider->Statamic\\Eloquent\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#1 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#2 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('Statamic\\\\Eloque...', Array, false)
#3 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Container/Container.php(283): Illuminate\\Foundation\\Application->resolve('Statamic\\\\Eloque...', Array, false)
#4 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#5 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#6 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve('Statamic\\\\Contra...', Array, true)
#7 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Foundation\\Application->resolve('Statamic\\\\Contra...', Array)
#8 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make('Statamic\\\\Contra...', Array)
#9 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Statamic\\\\Contra...', Array)
#10 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Stache/Repositories/EntryRepository.php(85): app('Statamic\\\\Contra...')
#11 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Stache\\Repositories\\EntryRepository->query()
#12 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionsController.php(29): Illuminate\\Support\\Facades\\Facade::__callStatic('query', Array)
#13 [internal function]: Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController->Statamic\\Http\\Controllers\\CP\\Collections\\{closure}(Object(Statamic\\Entries\\Collection), 0)
#14 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(630): array_map(Object(Closure), Array, Array)
#15 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Controllers/CP/Collections/CollectionsController.php(39): Illuminate\\Support\\Collection->map(Object(Closure))
#16 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController->index()
#17 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#18 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Collections\\CollectionsController), 'index')
#19 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#20 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Routing\\Route->run()
#21 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/CP/ControlPanel.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ControlPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#40 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#50 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#51 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#52 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#53 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/mooky/Code/stellaprojects/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/mooky/Code/stellaprojects/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/mooky/Code/stellaprojects/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/mooky/Code/stellaprojects/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#74 /Users/mooky/Code/stellaprojects/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#75 /Users/mooky/Code/stellaprojects/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#76 /Users/mooky/.composer/vendor/laravel/valet/server.php(214): require('/Users/mooky/Co...')
#77 {main}
"} 
```

**Comment by lrtrime** [comment]
I have the same here, found any solution? :)

**Comment by Joe2824** [comment]
Same error with
`Statamic 3.1.5 Pro
Laravel 8.34.0
PHP 8.0.3
mattrothenberg/statamic-mapbox-address 0.6.0
rias/statamic-redirect 1.4.3`

**Comment by kaznoble** [comment]
Anyone resolved this issue?

**Comment by enespolat24** [comment]
when you change model to UuidEntryModel , do not change array key . keep it like this
![image](https://user-images.githubusercontent.com/21336979/149524862-9a504bd8-1e12-4c04-a0d0-b103eb91bf88.png)
